CC = clang
NAME = {{ name }}
HEADER = includes/
SRC = srcs/
CS = {{ main }}
OBJS = $(patsubst %.c, %.o, $(CS))
SRCS = $(addprefix $(SRC), $(CS))
CFLAGS = -Wall -Wextra -Werror -I$(HEADER)
ifeq ($(CDEBUG), 1)
	CFLAGS += -g
endif
{% if libft_path %}CFLAGS += -I./libft/includes{% endif %}
{% if libft_path %}LIBOPT = -L./libft/ -lft{% endif %}

all: $(NAME)

$(NAME): {% if libft_path %}./libft/libft.a {% endif %}
	$(CC) $(CFLAGS) -c $(SRCS)
	$(CC) $(CFLAGS) $(LIBOPT) $(OBJS) -o $(NAME)

clean:
	/bin/rm -f $(OBJS)

fclean: clean
	/bin/rm -rf $(NAME)

re: fclean all
